### ISSUE TITLE
Update web site appearance

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/ChurchAppsWeb#3]
The current website borrows heavily from CHUMS.  Update the look of the site so it doesn't look so much like CHUMS, even if that just means changing the color scheme and backgrounds.

**Comment by pranavmalvawala** [comment]
Can you create a Mock up? @jzongker I'll be happy to implement it in the code

**Comment by mbyrdLCS** [comment]
churchapps.org

**Comment by mbyrdLCS** [comment]
I have Someone working on this also
